import {
    AccountCircle,
    Alarm,
    Article,
    Build,
    Call,
    CalendarToday,
    CameraAlt,
    Cloud,
    Dashboard,
    Email,
    Favorite,
    Home,
    Info,
    LocationOn,
    Lock,
    MenuBook,
    Notifications,
    Person,
    Phone,
    Print,
    Save,
    Search,
    Security,
    Settings,
    ShoppingCart,
    Star,
    ThumbUp,
    Visibility,
    Wifi,
    Work,
    ZoomIn,
    ArrowBack,
    ArrowForward,
    AttachFile,
    Backup,
    Bookmark,
    Check,
    Delete,
    Edit,
    FileCopy,
    Help,
    History,
    Keyboard,
    Launch,
    Link,
    List,
    Map,
    Palette,
    Power,
    Radio,
    Restore,
    Share,
    TrendingUp,
    Verified,
  } from "@mui/icons-material";
  
  export const iconMapping = {
    account_circle: AccountCircle,
    alarm: Alarm,
    article: Article,
    build: Build,
    call: Call,
    calendar_today: CalendarToday,
    camera_alt: CameraAlt,
    cloud: Cloud,
    dashboard: Dashboard,
    email: Email,
    favorite: Favorite,
    home: Home,
    info: Info,
    location_on: LocationOn,
    lock: Lock,
    menu_book: MenuBook,
    notifications: Notifications,
    person: Person,
    phone: Phone,
    print: Print,
    save: Save,
    search: Search,
    security: Security,
    settings: Settings,
    shopping_cart: ShoppingCart,
    star: Star,
    thumb_up: ThumbUp,
    visibility: Visibility,
    wifi: Wifi,
    work: Work,
    zoom_in: ZoomIn,
    arrow_back: ArrowBack,
    arrow_forward: ArrowForward,
    attach_file: AttachFile,
    backup: Backup,
    bookmark: Bookmark,
    check: Check,
    delete: Delete,
    edit: Edit,
    file_copy: FileCopy,
    help: Help,
    history: History,
    keyboard: Keyboard,
    launch: Launch,
    link: Link,
    list: List,
    map: Map,
    palette: Palette,
    power: Power,
    radio: Radio,
    restore: Restore,
    share: Share,
    trending_up: TrendingUp,
    verified: Verified,
  };
  