import {
    AccountCircle,
    Alarm,
    Article,
    Build,
    Call,
    CalendarToday,
    CameraAlt,
    Cloud,
    Dashboard,
    Email,
    Favorite,
    Home,
    Info,
    LocationOn,
    Lock,
    MenuBook,
    Notifications,
    Person,
    Phone,
    Print,
    Save,
    Search,
    Security,
    Settings,
    ShoppingCart,
    Star,
    ThumbUp,
    Visibility,
    Wifi,
    Work,
    ZoomIn,
    ArrowBack,
    ArrowForward,
    AttachFile,
    Backup,
    Bookmark,
    Check,
    Delete,
    Edit,
    FileCopy,
    Help,
    History,
    Keyboard,
    Launch,
    Link,
    List,
    Map,
    Palette,
    Power,
    Radio,
    Restore,
    Share,
    TrendingUp,
    Verified,
    AccountBalance,
    AccountBalanceWallet,
    AttachMoney,
    MonetizationOn,
    Money,
    Payment,
    Receipt,
    Savings,
    PriceChange,
    PriceCheck,
    AddShoppingCart,
    Analytics,
    Assessment,
    AutoGraph,
    Balance,
    BarChart,
    Category,
    CompareArrows,
    CreditCard,
    DonutSmall,
    Equalizer,
    EventNote,
    FactCheck,
    Inventory,
    Leaderboard,
    LocalAtm,
    Loyalty,
    Percent,
    RequestQuote,
    ShowChart,
    School,
    Class,
    Grade,
    LibraryBooks,
    Science,
    Computer,
    Book,
    Quiz,
    AutoStories,
    DocumentScanner,
    HistoryEdu,
    Language,
    Calculate,
    Engineering,
    Group,
    LaptopChromebook,
    AddAPhoto,
    Camera,
    CameraEnhance,
    CameraRoll,
    Collections,
    Crop,
    Filter,
    Image,
    Landscape,
    Panorama,
    Photo,
    PhotoAlbum,
    PhotoCamera,
    Slideshow,
    Timelapse,
    Wallpaper,
    LocalPharmacy,
    LocalHospital,
    Medical,
    MedicalServices,
    Medication,
    MedicationLiquid,
    Pills,
    Vaccines,
    Healing,
    HealthAndSafety,
    Emergency,
    BloodType,
    Biotech,
    MonitorHeart,
    Psychology,
    Sick,
    Warning,
    CheckCircle,
    Error,
    Thermostat,
    Schedule,
    Timer,
    AddCircle,
    RemoveCircle,
    Refresh,
    Sync,
    VerifiedUser,
    Shield,
    ReportProblem,
    NotificationImportant,
    Factory,
  } from "@mui/icons-material";
  
  export const iconMapping = {
    account_circle: AccountCircle,
    alarm: Alarm,
    article: Article,
    build: Build,
    call: Call,
    calendar_today: CalendarToday,
    camera_alt: CameraAlt,
    cloud: Cloud,
    dashboard: Dashboard,
    email: Email,
    favorite: Favorite,
    home: Home,
    info: Info,
    location_on: LocationOn,
    lock: Lock,
    menu_book: MenuBook,
    notifications: Notifications,
    person: Person,
    phone: Phone,
    print: Print,
    save: Save,
    search: Search,
    security: Security,
    settings: Settings,
    shopping_cart: ShoppingCart,
    star: Star,
    thumb_up: ThumbUp,
    visibility: Visibility,
    wifi: Wifi,
    work: Work,
    zoom_in: ZoomIn,
    arrow_back: ArrowBack,
    arrow_forward: ArrowForward,
    attach_file: AttachFile,
    backup: Backup,
    bookmark: Bookmark,
    check: Check,
    delete: Delete,
    edit: Edit,
    file_copy: FileCopy,
    help: Help,
    history: History,
    keyboard: Keyboard,
    launch: Launch,
    link: Link,
    list: List,
    map: Map,
    palette: Palette,
    power: Power,
    radio: Radio,
    restore: Restore,
    share: Share,
    trending_up: TrendingUp,
    verified: Verified,
    account_balance: AccountBalance,
    account_balance_wallet: AccountBalanceWallet,
    attach_money: AttachMoney,
    monetization_on: MonetizationOn,
    money: Money,
    payment: Payment,
    receipt: Receipt,
    savings: Savings,
    price_change: PriceChange,
    price_check: PriceCheck,
    add_shopping_cart: AddShoppingCart,
    analytics: Analytics,
    assessment: Assessment,
    auto_graph: AutoGraph,
    balance: Balance,
    bar_chart: BarChart,
    category: Category,
    compare_arrows: CompareArrows,
    credit_card: CreditCard,
    donut_small: DonutSmall,
    equalizer: Equalizer,
    event_note: EventNote,
    fact_check: FactCheck,
    inventory: Inventory,
    leaderboard: Leaderboard,
    local_atm: LocalAtm,
    loyalty: Loyalty,
    percent: Percent,
    request_quote: RequestQuote,
    show_chart: ShowChart,
    school: School,
    class: Class,
    grade: Grade,
    library_books: LibraryBooks,
    science: Science,
    computer: Computer,
    book: Book,
    quiz: Quiz,
    auto_stories: AutoStories,
    document_scanner: DocumentScanner,
    history_edu: HistoryEdu,
    language: Language,
    calculate: Calculate,
    engineering: Engineering,
    group_study: Group,
    laptop_chromebook: LaptopChromebook,
    add_a_photo: AddAPhoto,
    camera: Camera,
    camera_enhance: CameraEnhance,
    camera_roll: CameraRoll,
    collections: Collections,
    crop: Crop,
    filter: Filter,
    image: Image,
    landscape: Landscape,
    panorama: Panorama,
    photo: Photo,
    photo_album: PhotoAlbum,
    photo_camera: PhotoCamera,
    slideshow: Slideshow,
    timelapse: Timelapse,
    wallpaper: Wallpaper,
    pharmacy: LocalPharmacy,
    hospital: LocalHospital,
    medical: Medical,
    medical_services: MedicalServices,
    medication: Medication,
    liquid_medication: MedicationLiquid,
    pills: Pills,
    tablets: Pills,
    capsules: Medication,
    vaccines: Vaccines,
    injection: Vaccines,
    syringe: Vaccines,
    prescription: Receipt,
    drug_info: Info,
    dosage: Balance,
    side_effects: Warning,
    contraindications: Error,
    drug_interaction: CompareArrows,
    clinical_trial: Science,
    lab_test: Science,
    biotech: Biotech,
    research: Science,
    manufacturing: Factory,
    quality_control: VerifiedUser,
    safety: Shield,
    adverse_reaction: ReportProblem,
    drug_alert: NotificationImportant,
    expiry_date: Schedule,
    timer_medication: Timer,
    add_medication: AddCircle,
    remove_medication: RemoveCircle,
    refill: Refresh,
    sync_medication: Sync,
    patient_monitoring: MonitorHeart,
    treatment: Healing,
    therapy: Psychology,
    emergency_medication: Emergency,
    blood_work: BloodType,
    temperature: Thermostat,
    health_status: HealthAndSafety,
    patient_sick: Sick,
    recovery: CheckCircle,
  };
  