import {
    AccountCircle,
    Alarm,
    Article,
    Build,
    Call,
    CalendarToday,
    CameraAlt,
    Cloud,
    Dashboard,
    Email,
    Favorite,
    Home,
    Info,
    LocationOn,
    Lock,
    MenuBook,
    Notifications,
    Person,
    Phone,
    Print,
    Save,
    Search,
    Security,
    Settings,
    ShoppingCart,
    Star,
    ThumbUp,
    Visibility,
    Wifi,
    Work,
    ZoomIn,
    ArrowBack,
    ArrowForward,
    AttachFile,
    Backup,
    Bookmark,
    Check,
    Delete,
    Edit,
    FileCopy,
    Help,
    History,
    Keyboard,
    Launch,
    Link,
    List,
    Map,
    Palette,
    Power,
    Radio,
    Restore,
    Share,
    TrendingUp,
    Verified,
    AccountBalance,
    AccountBalanceWallet,
    AttachMoney,
    MonetizationOn,
    Money,
    Payment,
    Receipt,
    Savings,
    PriceChange,
    PriceCheck,
    AddShoppingCart,
    Analytics,
    Assessment,
    AutoGraph,
    Balance,
    BarChart,
    Category,
    CompareArrows,
    CreditCard,
    DonutSmall,
    Equalizer,
    EventNote,
    FactCheck,
    Inventory,
    Leaderboard,
    LocalAtm,
    Loyalty,
    Percent,
    RequestQuote,
    ShowChart,
    School,
    Class,
    Grade,
    LibraryBooks,
    Science,
    Computer,
    Book,
    Quiz,
    AutoStories,
    DocumentScanner,
    HistoryEdu,
    Language,
    Calculate,
    Engineering,
    Group,
    LaptopChromebook,
  } from "@mui/icons-material";
  
  export const iconMapping = {
    account_circle: AccountCircle,
    alarm: Alarm,
    article: Article,
    build: Build,
    call: Call,
    calendar_today: CalendarToday,
    camera_alt: CameraAlt,
    cloud: Cloud,
    dashboard: Dashboard,
    email: Email,
    favorite: Favorite,
    home: Home,
    info: Info,
    location_on: LocationOn,
    lock: Lock,
    menu_book: MenuBook,
    notifications: Notifications,
    person: Person,
    phone: Phone,
    print: Print,
    save: Save,
    search: Search,
    security: Security,
    settings: Settings,
    shopping_cart: ShoppingCart,
    star: Star,
    thumb_up: ThumbUp,
    visibility: Visibility,
    wifi: Wifi,
    work: Work,
    zoom_in: ZoomIn,
    arrow_back: ArrowBack,
    arrow_forward: ArrowForward,
    attach_file: AttachFile,
    backup: Backup,
    bookmark: Bookmark,
    check: Check,
    delete: Delete,
    edit: Edit,
    file_copy: FileCopy,
    help: Help,
    history: History,
    keyboard: Keyboard,
    launch: Launch,
    link: Link,
    list: List,
    map: Map,
    palette: Palette,
    power: Power,
    radio: Radio,
    restore: Restore,
    share: Share,
    trending_up: TrendingUp,
    verified: Verified,
    account_balance: AccountBalance,
    account_balance_wallet: AccountBalanceWallet,
    attach_money: AttachMoney,
    monetization_on: MonetizationOn,
    money: Money,
    payment: Payment,
    receipt: Receipt,
    savings: Savings,
    price_change: PriceChange,
    price_check: PriceCheck,
    add_shopping_cart: AddShoppingCart,
    analytics: Analytics,
    assessment: Assessment,
    auto_graph: AutoGraph,
    balance: Balance,
    bar_chart: BarChart,
    category: Category,
    compare_arrows: CompareArrows,
    credit_card: CreditCard,
    donut_small: DonutSmall,
    equalizer: Equalizer,
    event_note: EventNote,
    fact_check: FactCheck,
    inventory: Inventory,
    leaderboard: Leaderboard,
    local_atm: LocalAtm,
    loyalty: Loyalty,
    percent: Percent,
    request_quote: RequestQuote,
    show_chart: ShowChart,
    school: School,
    class: Class,
    grade: Grade,
    library_books: LibraryBooks,
    science: Science,
    computer: Computer,
    book: Book,
    quiz: Quiz,
    auto_stories: AutoStories,
    document_scanner: DocumentScanner,
    history_edu: HistoryEdu,
    language: Language,
    calculate: Calculate,
    engineering: Engineering,
    group_study: Group,
    laptop_chromebook: LaptopChromebook,
  };
  